### ISSUE TITLE
From the Brain python bindings, one can't get version information

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/Brion#155]
Maybe a  __version__ or/and getBrionVersion would be helpful.

**Comment by hernando** [comment]
Is __version__ the standard way of providing version information in packages?

**Comment by mgeplf** [comment]
Sadly there's no standard that everyone uses, but numpy/pandas/h5py all have `__version__`.  Numpy and h5py also have a submodule `.version.` with further information underneath (underlying library version, whether it's a release, etc).

I think it would make sense to:
1) Have __version__ with the Brain version
2) Have version.brion to say what the brion version has been wrapped

**Comment by hernando** [comment]
That sound easy to do, but there's something I don't get. If version is an object, how is it supposed to store the version number, with __repr__? or did you mean version.version?

**Comment by mgeplf** [comment]
Sorry I wasn't clear, itt has members, ex:
```
import numpy as np
vars(np.version)
[snip]
 'full_version': '1.11.0',
 'git_revision': '4092a9e160cc247a4a45724579a0c829733688ca',
 'release': True,               
 'short_version': '1.11.0',   
 'version': '1.11.0'}
```

**Comment by tribal-tec** [comment]
__version__ added in https://github.com/BlueBrain/Brion/pull/160
