### ISSUE TITLE
Missing OSX wheel ?

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Brion#183]
I'm converting BGLibPy so that it works with the latest version of BluePy.
Unfortunately this version seems to depend on Brion now. When I try to install on OS X, I get the following error:
Collecting brain<4.0,>=3.0 (from bluepy[bbp]->bglibpy==3.0)
  Could not find a version that satisfies the requirement brain<4.0,>=3.0 (from bluepy[bbp]->bglibpy==3.0) (from versions: )
No matching distribution found for brain<4.0,>=3.0 (from bluepy[bbp]->bglibpy==3.0)

Could it be that our devpi server is missing an OSX wheel for brain/brion ?

**Comment by hernando** [comment]
Yes, we are aware that this wheel is missing, we didn't provide it so far because there have been higher priority things to do. Next Monday we have planning, so we will schedule it.

**Comment by wvangeit** [comment]
Did you decide on a timeline for this ?

**Comment by hernando** [comment]
I'll answer you tomorrow in a private mail.

**Comment by arsenius7** [comment]
Juan, can I know the secret as well? :)
Thanks.

**Comment by hernando** [comment]
I planned to look into it this sprint, but too unexpected things have popped up and I'm not sure I'll have time to look into it.

**Comment by arsenius7** [comment]
Not sure if I mentioned it before, but due to the lack of OSX wheel we have to support _both_ `Brion` and `pybinreports` for report access in BluePy.
I would appreciate the possibility to drop `pybinreports` along with the temporary scaffold for supporting two I/O layer libraries. :)

**Comment by hernando** [comment]
I have a script to generate the wheels ready, but I'm stuck with a problem detecting HDF5 in the Jenkins plan. I'll keep you posted about it.

**Comment by arsenius7** [comment]
Hi, Juan.
Any luck in your battle vs Jenkins & HDF5? :)

**Comment by hernando** [comment]
I got desperate because every change I try takes several minutes to give me a result and I'm still clueless. I even tried setting the full path to the headers and libs in the cmake command line and it doesn't work either. So I let it rest for a few days to push forward other work that has deadlines.
I'll give it a try again today.

**Comment by hernando** [comment]
I made progress, but know it's the boost detection which is not working as expected. Due to this issue I could only generate the wheel for 2.7.14 for the moment, but it's not uploaded yet. I'll continue tomorrow.

**Comment by arsenius7** [comment]
I am sorry for yet another bump; but seeing how much time it takes to get a wheel, I start to feel uneasy about the decision to abandon `pybinreports` in favor of Brion.

No blame intended, I'm aware that you have higher priorities, but we have to factor it in for the future situations as well.

Is there anything we can do from our side to facilitate the task? (and not just bump it :) )

**Comment by hernando** [comment]
I have 4 wheels that I built in my laptop for Python 2.7, 3.4, 3.5 and 3.6 weeks ago during the process of writing the CI script. If you know how to upload them to DevPy without requiring a Jenkins job we can do it immediately.

Last Wednesday I tried to fix the boost detection problem in the osx-testing build bot, but I didn't succeed (it was quite frustrating in fact). I don't know if you can help very much here.

**Comment by arsenius7** [comment]
> If you know how to upload them to DevPy without requiring a Jenkins job we can do it immediately.
I guess INFRA does know; I've asked for that with first version of `pybinreports`.

**Comment by hernando** [comment]
I have uploaded 4 Mac OS/X wheels to our internal Python repository.
* brain-3.0.0-cp27-cp27m-macosx_10_9_intel.whl
* brain-3.0.0-cp34-cp34m-macosx_10_9_intel.whl
* brain-3.0.0-cp35-cp35m-macosx_10_9_intel.whl
* brain-3.0.0-cp36-cp36m-macosx_10_9_intel.whl

I still have to do some work for finishing with the automation, but it's not a big deal

**Comment by arsenius7** [comment]
Thanks, Juan.

Unfortunately,  I'm getting ``No plugin implementation available`` for both .bbp and .h5 reports (Python 2.7 / 3.6).

**Comment by hernando** [comment]
I'm getting the same in the laptop, bad testing on my side. This is related to the static linking, I didn't expect it to happen, but I have an idea about what can be the reason.

**Comment by hernando** [comment]
The problem should be fixed now

**Comment by arsenius7** [comment]
Thanks, Juan, this one is working fine.
I've stumbled upon another [issue](https://github.com/BlueBrain/Brion/issues/215) while testing it, but that's a different story.
I guess we'll keep this one open until wheel deployment is automatic?

**Comment by hernando** [comment]
Yes, I won't close it until all related PR's are merged.
