### ISSUE TITLE
Brain 3.0.0 reports wrong gids in soma voltage report

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Brion#199]
After upgrading to Brain 3.0.0 my BGLibPy jenkins plans are failing, because a certain gid can't be found in a soma.bbp voltage report.
I'm reading the report through BluePy, but the core issue seems to be the following.
I have attached a soma.bbp. When reading this file using:
`
import brain; reader = brain.CompartmentReport('soma.bbp'); print(reader.gids)
`
I get in 2.1.0:
[1]
in 3.0.0:
[16777216]

(the soma.bbp only has one gid I think, and it should be 1)

[soma.bbp.zip](https://github.com/BlueBrain/Brion/files/1534565/soma.bbp.zip)

**Comment by hernando** [comment]
That's really strange, I'll look into it immediately. Can you make that report available to me?

**Comment by wvangeit** [comment]
I have attached it in the top comment ?

**Comment by hernando** [comment]
Sorry, I clearly read attached, but I was looking for the attachment somewhere else (too many different GUIs are getting me confused)

**Comment by hernando** [comment]
I spotted the bug. It was related to little/big endian differences. The tests didn't discover it because all the data is big endian.

**Comment by wvangeit** [comment]
Ok, thanks. Please let me know when there is a new devpi package available.
Maybe you can use that soma.bbp in your tests :-)

**Comment by hernando** [comment]
The wheel has been updated, I haven't touched the version yet as we need more thinking into that and this was a critical bug.

**Comment by wvangeit** [comment]
Ok, thanks. The BGLibPy tests are passing with the new version.

**Comment by hernando** [comment]
You should also perceive it faster that before.
