### ISSUE TITLE
Allow JSON input instead of a CircuitConfig file

### ISSUE THREAD

**Issue by nantille** [BlueBrain/Brion#207]
Currently, Brain Python API needs a CircuitConfig ascii file to give circuit, synapse report and other paths.

I request to have the option to pass a JSON config (as a string or as a .json file) to the constructor of brain.Circuit. That JSON would have the paths embedded into it. This way relative paths can be handled dynamically in Python before passing that to the JSON string and to the constructor.

**Comment by jplanasc** [comment]
I think this request is outdated and doesn't make sense now that we have SONATA on its way.
