### ISSUE TITLE
Support for loading morphologies from memory buffer

### ISSUE THREAD

**Issue by tribal-tec** [BlueBrain/Brion#220]
Today, swc and h5 morphologies can only be loaded from file/disk. Adding support to parse and create them from a memory buffer is necessary in a client-server architecture where the data blob is passed by the client containing the file content.

For hdf5 support, an according change in HighFive is request here: https://github.com/BlueBrain/HighFive/issues/105

**Comment by rolandjitsu** [comment]
@straaljager this feature is essential for loading morphology files in Brayns over binary socket (upload from client - notebooks/web app). Do you think we could allocate someone from our team to work on it?

**Comment by straaljager** [comment]
Sure thing. Let's put it on the agenda for the next viz team meeting (probably tomorrow)

**Comment by straaljager** [comment]
@hernando can you pls have a look this?

**Comment by hernando** [comment]
Will do when I'm done with the open stories.
