### ISSUE TITLE
Convertion to Janelia Farms MouseLight SWC files fails

### ISSUE THREAD

**Issue by christian-oreilly** [BlueBrain/Brion#221]
The morphologyConverter crashes when trying to convert swc morphologies from Janelia Farms MouseLight (http://ml-neuronbrowser.janelia.org/) to h5.

```
Processing ./swc/AA0302.swc file...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Reading swc morphology file: ./swc/AA0302.swc, parse error at line 9
Aborted (core dumped)
Processing ./swc/Halnes20
```

This is systematic with their morphologies. This issue **might** (not sure) be related with issue https://github.com/BlueBrain/Brion/issues/98, which has been filed a while ago.

**Comment by hernando** [comment]
I could not reproduce the problem with the AA0302.swc file I downloaded from the web page.

**Comment by christian-oreilly** [comment]
Could it be a version issue (i.e., a previous bug that is now fixed)? I use the brion NIX module on the Lugano cluster.

**Comment by hernando** [comment]
The binary from the NIX module also fails with the same file. I'm quite surprised because the code hasn't been touched in months.

**Comment by hernando** [comment]
I see now what the problem is, and it was solved in November last year, but the NIX module has not been updated since. The original parser was not accepting tabs as separators between the numbers.
