### ISSUE TITLE
Fix warning message

### ISSUE THREAD

**Issue by nantille** [BlueBrain/Brion#228]
I get the following warning when using Brion with the python bindings.

  PID.Thread  | Filename:line                    |   ms | Message
49802.Unknown           ../brion/synapse.cpp:98        0 Could not open synapse file /[my_circuit_path]/somatosensory_cxs1_v5.r0/ncsFunctionalAllRecipePathways/nrn_extra.h5: Unable to open file /[my_circuit_path]/somatosensory_cxs1_v5.r0/ncsFunctionalAllRecipePathways/nrn_extra.h5 (File accessibilty) Unable to open file

After asking James King about it, nrn_extra.h5 is something that is to be removed so a warning about it should not appear.

**Comment by jplanasc** [comment]
Outdated.
