### ISSUE TITLE
With some gcc versions, std::call_once deadlocks after the first call has thrown an exception

### ISSUE THREAD

**Issue by hernando** [BlueBrain/Brion#232]
Some functions are using std::call_once, for example those that ensure that synapses positions and attributes are loaded. The problem is that if the function called by call_once throws an exception, any subsequent call deadlocks inside pthread. The only solution seems to be to change the implementation to use a mutex, which is exactly what we want to avoid by using call_once.

More details and pointers about the gcc can be found [here](https://github.com/PaddlePaddle/Paddle/issues/6681)

**Comment by hernando** [comment]
This will probably get solved in gcc 9: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66146

**Comment by jplanasc** [comment]
Outdated.
