### ISSUE TITLE
`brain.CompartmentView.load` hangs on low-memory machine

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/Brion#248]
We are facing some weird problem when using `brain` for accessing binary reports on 500MB virtual machine.

```
import brain
rep = brain.CompartmentReport(<1MB binary report, apparently valid>)
view = rep.create_view()
view.load_all()  # works fine
view.load(0.0, 1.0) # works fine
view.load(0.0, 1.0, 0.1) # hangs
```

While it seems to be an edge case, I wonder what can be the reason for such behavior (is it related to limited memory?).

An example of such machine: `159.100.241.59` (test report could be found in `\root` folder there); please ask @antonelepfl for access.

Latest `brain` wheel fetched from BBP devpi was used for testing.
All the methods work fine on 2GB virtual machine.

**Comment by jplanasc** [comment]
Outdated.
