### ISSUE TITLE
Python 3.7 package on devpi

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Brion#254]
Could you build and upload a brain package for python 3.7 (to our devpi server). 
Thanks.

**Comment by hernando** [comment]
I started this before the Christmas break but it wasn't possible to get it done as quickly as I thought. I was having problems compiling Boost.Python with Python 3.7 and it doesn't look particularly good. I came back from holidays today, so give me a day or two to get it done.

**Comment by wvangeit** [comment]
Ok, thanks.

**Comment by hernando** [comment]
The wheel for Python 3.7 for Mac and Linux has been uploaded. Let me know if it works for you so I can close this ticket.

**Comment by wvangeit** [comment]
That worked. Thanks.
