### ISSUE TITLE
Morphology extensions for Glial cells

### ISSUE THREAD

**Issue by eile** [BlueBrain/Brion#26]
* cross-section is an ellipse, not a circle (needs two axis per point, and their orientation)
* Need to store cross-section perimeter (length of cross-section shape) - this is the real shape's length, different from the ellipse perimeter.
* helper function to get cross-section area at point (elipse has same area as original cross-section shape)

**Comment by eile** [comment]
Reported by Dan Keller

**Comment by hernando** [comment]
This is a major overhaul of the morphology file, not only the Brion's API. Are other teams involved in this epic?

**Comment by eile** [comment]
I guess not.

**Comment by bilgili** [comment]
This is not an extension, this is Morphology V3

**Comment by eile** [comment]
Workflow is:
* reconstructed glial mesh
* transformed into a morphological skeleton as described above
* Skeleton (and synthetic derived skeletons) are read into a model building step
* Model building transforms skeleton and generates mesh which is space filling
* mesh is written out for simulator

**Comment by eile** [comment]
Ok, this is a superset of the current morphology, storing:
* two radii and the perimeter per endpoint
* 0 or 1 morphological skeleton, reconstructed or synthetic
* 0..N mesh representations, reconstructed|synthetic, illustrative

Later:
* Algorithms to simplify skeletons (for vis and/or sim)
* Algorithms to create illustrative meshes

**Comment by tribal-tec** [comment]
https://github.com/BlueBrain/Brion/pull/75: Support for perimeter

**Comment by eile** [comment]
Considered implemented until there are new feature requests.
