### ISSUE TITLE
Re-use `libsonata` for accessing SONATA node / edge populations

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/Brion#260]
Now that [`libsonata`](https://github.com/bluebrain/libsonata) is open-sourced, we can consider re-using it for accessing node / edge populations.

Also, we can look into moving to `libsonata` implementation for accessing SONATA networks configs (https://github.com/BlueBrain/libsonata/issues/4) and binary simulation reports (https://github.com/BlueBrain/libsonata/issues/7).

**Comment by jplanasc** [comment]
As of today, this seems outdated.
