### ISSUE TITLE
`brain.CompartmentReport.create_view` does not support `np.uint8/16/32/64` gid arrays

### ISSUE THREAD

**Issue by tomdele** [BlueBrain/Brion#264]
We sometimes use gids with `np.uint` dtypes, but the `brain.CompartmentReport.create_view` does not accept them.

```
import brain
import numpy as np
reader = brain.CompartmentReport(soma.bbp")
reader.create_view(np.array([1, 2, 3], dtype=np.uint64))
```
raises: 
```
Traceback (most recent call last):
    reader.create_view(np.array([1, 2, 3], dtype=np.uint64))
ValueError: Cannot convert numpy array of type u8 to GID set
```
It would be great if you can add these feature to the `brain.CompartmentReport.create_view` method.

**Comment by jplanasc** [comment]
@tomdele I guess this is not relevant anymore, so I'm closing the issue.

**Comment by tomdele** [comment]
indeed np !
