### ISSUE TITLE
Wrong values returned when reading soma.bbp report

### ISSUE THREAD

**Issue by seirios** [BlueBrain/Brion#292]
When reading voltage traces from a soma.bbp report file through bluepy, which uses brain to read theses kinds of reports, I'm getting different values from what's actually stored in the file, as assessed using somaDump from reportinglib. Some values appear duplicated and it looks like this:

<img width="952" alt="Screenshot 2020-08-10 at 10 57 28" src="https://user-images.githubusercontent.com/7497849/89766665-cdefa280-daf8-11ea-906d-03a7f7f9de4d.png">

Mike Gevaert has confirmed that this is an issue with brain and not bluepy itself in BLPY-215.

**Comment by NadirRoGue** [comment]
This issue was resolved in #295
