### ISSUE TITLE
Compiling without BBPTestData create missing symbols

### ISSUE THREAD

**Issue by adevress** [BlueBrain/Brion#96]
Hi,

Compiling Brion without the BBPTestData create undefined reference in the brion python module.

e.g

ldd -r _brain.so

undefined symbol: _ZN5brain11export_testEv	(/nix/store/3jgfsr1282ls5xhv0dsicl066kw14nqi-generated-env-module-rtneuron/lib/python2.7/site-packages/brain/_brain.so)

I will add a patch for that on the boost python pull request

**Comment by hernando** [comment]
Fixed by 0877e10
